#!/usr/bin/env bash
# this script is for print a string 10 times using until loop

cnt=0

until false; do
  echo "Best School"
  ((cnt++))
  if [[ $cnt -lt 10 ]]; then
    continue
  else
    break
  fi
done
