#!/usr/bin/env bash
# this script is for 4 bad luck, 8 is your chance

cnt=1

while [ "$cnt" -lt 11 ]; do

  # if 4 bad luck elif 8 good luck
  if [ "$cnt" -eq 4 ]; then
    echo "bad luck"
  elif [ "$cnt" -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi

  ((cnt++))
done
