#!/usr/bin/env bash
# this script is for display time for 12 hours and 59 minutes

hr=0

while [ "$hr" -le 12 ]; do
  echo "Hour: $hr"
  
  mnt=1
  
  while [ "$mnt" -lt 60 ]; do
    echo "$mnt"
    minute=$((mnt + 1))
  done

  hr=$((hr + 1))
done
