#!/usr/bin/env bash
# displays information about file 'school'



# checks if file exists
if [ -e "$school" ]; then

  echo "school file exists"

  # checks if file is empty
  if [ ! -s "$school" ]; then
    echo "school file is empty"

    # checks if file is a regular file
    if [ -f "$school" ]; then
      echo "school is a regular file"
    fi  

  else

    echo "school file is not empty"

    # checks if file is a regular file
    if [ -f "$school" ]; then
      echo "school is a regular file"
    fi  
  
  fi

else
  
  echo "school file does not exist"

fi
